notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src apiaryio/emcc:latest bash

script:
  - docker exec -it emscripten emmake make
  - npm run test