title: Wist
description: A linter tool for identifying and reporting on patterns in BrightScript.
baseurl: "/wist"
url: https://willowtreeapps.github.io
twitter_username: willowtreeapps
github_username:  willowtreeapps
markdown: kramdown
includes_dir: resources/_includes
layouts_dir: resources/_layouts
sass:
  sass_dir: resources/_assets/stylesheets
  style: compressed

# Custom variables
current_version: 1.0.0-beta.1
logo: wist-logo
